import REPL

const OUTPUT = joinpath(@__DIR__, "..", "src", "unicodeCompletions.generated.ts")

function ts_escape(s::AbstractString)
    buffer = IOBuffer()
    for char in s
        if char == '\\'
            print(buffer, "\\\\")
        elseif char == '\''
            print(buffer, "\\'")
        elseif char == '\n'
            print(buffer, "\\n")
        elseif char == '\r'
            print(buffer, "\\r")
        elseif char == '\t'
            print(buffer, "\\t")
        else
            print(buffer, char)
        end
    end
    return String(take!(buffer))
end

emoji_symbols = isdefined(REPL.REPLCompletions, :emoji_symbols) ? REPL.REPLCompletions.emoji_symbols : Pair{String,String}[]
entries = sort!(collect(Iterators.flatten((REPL.REPLCompletions.latex_symbols, emoji_symbols))); by=first)

open(OUTPUT, "w") do io
    println(io, "// This file is generated by scripts/generate_unicode_completions.jl.")
    println(io, "// Do not edit by hand.")
    println(io)
    println(io, "export type UnicodeCompletionEntry = readonly [label: string, value: string]")
    println(io)
    println(io, "export const UNICODE_COMPLETIONS: readonly UnicodeCompletionEntry[] = [")
    for (label, value) in entries
        println(io, "  ['$(ts_escape(string(label)))', '$(ts_escape(string(value)))'],")
    end
    println(io, "]")
end
